version: '3.8'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        env_file:
            - secrets/postgres.env
        ports:
            - "5432:5432"  # Expose the default PostgreSQL port
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: ednarb29/docker-airflow:2.2.3
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        env_file:
            - secrets/fernet_key.env
            - secrets/postgres.env
            - .env
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "./dags:${AIRFLOW_DAG_DIR}"
            # - "./plugins:${AIRFLOW_PLUGINS_DIR}"
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
